server/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

server/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('recommend.urls')),
    path('faceswap/', include('faceswap.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/faceswap/urls.py
from django.urls import path
from . import views

app_name = 'faceswap'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.ImageUpload.as_view(), name='upload_img'),
    path('swap/<int:id>', views.SwappingFace.as_view(), name='swap_face'),
]

server/recommend/urls.py
from django.urls import path

from . import views


app_name = 'recommend'


urlpatterns = [
    path('', views.ImageSearch.as_view(), name='search'),
    path('select/', views.ImagePick.as_view(), name='select'),
]

server/faceswap/models.py
from django.db import models


class ImageUploadModel(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.ImageField(upload_to='images/%Y/%m/%d')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    target_image = models.ImageField(upload_to='target_images/')
    source_image = models.ImageField(upload_to='source_images/')
    result_image = models.ImageField(upload_to='result_images/%Y/%m/%d', blank=True, null=True)

server/recommend/models.py
from django.db import models

# Create your models here.

server/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "password1", "password2")

server/faceswap/forms.py
from django import forms
from .models import ImageUploadModel


# simple upload form
class SimpleUploadForm(forms.Form):
    title = forms.CharField(max_length=50)
    image = forms.ImageField()  # file field + image


# description 추가
class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = ImageUploadModel
        fields = ('source_image', )

server/recommend/forms.py
# forms.py 파일에 추가
from django import forms


class SearchForm(forms.Form):
    sentence = forms.CharField(label='문장을 입력하세요', widget=forms.TextInput(attrs={'class': 'form-control'}))

server/accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from accounts.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form': form})

server/faceswap/views.py
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from django.urls import reverse

from .forms import SimpleUploadForm, ImageUploadForm
from .models import ImageUploadModel
from .utils import cv_swap_face, face_bbox

import requests


class ImageUpload(APIView):
    def get(self, request):
        form = ImageUploadForm()  # GET reuest
        return render(request, 'faceswap/img_upload.html', {'form': form})

    def post(self, request):
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            source_image = request.FILES['source_image']

            post.source_image = source_image
            post.save()

            target_image_s3_url = request.POST.get('target_image')
            target_image_content = requests.get(target_image_s3_url).content
            target_image_name = target_image_s3_url.split('/')[-1]
            target_image_path = f"target_images/{target_image_name}"  # 저장될 경로 설정
            default_storage.save(target_image_path, ContentFile(target_image_content))

            upload_image_model = ImageUploadModel.objects.create(
                                                                target_image=target_image_path,
                                                                source_image=source_image
                                                                )

        return redirect(reverse('faceswap:swap_face', kwargs={'id': upload_image_model.id}))


class SwappingFace(APIView):
    target_faces_sorted = None
    source_faces_sorted = None

    def get(self, request, id):
        upload_image_model = ImageUploadModel.objects.get(id=id)
        target_image = upload_image_model.target_image
        source_image = upload_image_model.source_image

        #얼굴 bbox
        target_bbox_list_json, source_bbox_list_json, target_faces_sorted, source_faces_sorted = face_bbox(target_image, source_image)

        SwappingFace.target_faces_sorted = target_faces_sorted
        SwappingFace.source_faces_sorted = source_faces_sorted
    
        context = {
            'target_bbox_json': target_bbox_list_json,
            'source_bbox_json': source_bbox_list_json,
            'img_model': upload_image_model
            }

        return render(request, 'faceswap/faceswap.html', context)
    
    def post(self, request, id):
        upload_image_model = ImageUploadModel.objects.get(id=id)
        target_image = upload_image_model.target_image
        source_image = upload_image_model.source_image

        target_checkboxes = [int(x) for x in request.POST.getlist('target_checkbox')]
        source_checkboxes = [int(x) for x in request.POST.getlist('source_checkbox')]

        result_url = cv_swap_face(target_image,
                                  source_image,
                                  SwappingFace.target_faces_sorted,
                                  SwappingFace.source_faces_sorted,
                                  target_checkboxes,
                                  source_checkboxes[0])  # machine learning

        upload_image_model.result_image = result_url
        
        context = {'swapped_img_url': result_url}

        return render(request, 'faceswap/faceswap.html', context)
        

server/recommend/views.py
from django.shortcuts import render
from rest_framework.views import APIView

from .forms import SearchForm
from .apps import RecommendConfig
from .utils import add_img_path


class ImageSearch(APIView):
    def get(self, request):
        form = SearchForm()
        return render(request, 'recommend/search.html', {'form': form})

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data.get('sentence')
            labels = RecommendConfig.model.inference(query)
            context = add_img_path(labels)
        else:
            return render(request, 'recommend/search.html', {'form': form})
        return render(request, 'recommend/select.html', context)


class ImagePick(APIView):
    def get(self, request):
        return render(request, 'recommend/select.html')

    def post(self, request):
        image_path = request.POST.get('selected_image')

        context = {
            'image_path': image_path,
        }

        return render(request, 'faceswap/img_upload.html', context)

server/templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accounts:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

server/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

server/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>deep daiv.</title>
    <!-- search CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;700;800;900&display=swap" rel="stylesheet">
    <!-- pretendard font -->
    <link rel="stylesheet" type="text/css" href='https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css'>
    <!-- Icon font -->
    <script src="https://kit.fontawesome.com/f5505320f2.js" crossorigin="anonymous"></script>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- select JS -->
<script src="{% static 'recommend/select.js' %}"></script>
</body>
</html>

server/templates/faceswap/faceswap.html
{% extends "base.html" %}
{% block content %}
<form id ="swapform"method="POST" action="/faceswap/swap/{{img_model.id}}">
  {% csrf_token %}
  {% if not swapped_img_url %}
  <div class="container">
    <h1 class="title">얼굴 인식 결과</h1>
    <h3 style="padding: 1rem;"> * 스와핑하고 싶은 얼굴을 선택해주세요</h3>
    <div class="row">
      <div class="col-md-6">
        <div class="image-container card">
          <h3 class="image-title" style="font-size: 20px; font-family: Poppins";>Target Image</h3>
          <div style="display: flex; justify-content: center;">
            <div id="target_image_container" data-mydata="{{ target_bbox_json|safe }}"  style="position: relative; text-align: center;">
              {% if img_model.target_image %}
              <img class="bbox_image" id="target_image" src="{{ img_model.target_image.url }}">
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="image-container card">
          <h3 class="image-title" style="font-size: 20px; font-family: Poppins;">Source Image</h3>
          <div style="display: flex; justify-content: center;">
            <div id="source_image_container" data-mydata="{{ source_bbox_json|safe }}" style="position: relative; text-align: center;">
              {% if img_model.source_image %}
              <!-- <img class="img"src="https://ifong-image-data.s3.ap-northeast-2.amazonaws.com/376.png" alt="이미지 2" class="img-fluid"> -->
              <img class="bbox_image" id="source_image" src="{{ img_model.source_image.url }}" >
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr style="margin: 2rem 0;">
    <div style="display: flex; justify-content: center; margin: 4vh;">
      <button type="submit" class="btn btn-primary" style="width: 20rem; font-size: 22px;">스와핑하기</button>
    </div>
  </div>
  {% else %}
  <div class="container">
    <h1 class="title">스와핑 결과</h1>
    <div class="row">
      <div class="col-md-12">
        <div class="image-container card">
          <div class="d-flex align-items-center justify-content-center">
            <img class="bbox_image" src="{{ swapped_img_url }}">
            <!-- <img class="bbox_image" src="{{ swapped_img_url }}"> -->
          </div>
        </div>
      </div>
    </div>
    <hr style="margin: 2rem 0;">
    <div style="display: flex; justify-content: space-evenly;">
      <a href="{% url 'recommend:search' %}" class="btn btn-primary" style="width: 20rem; font-size: 22px;">홈으로 이동</a>
    </div>
  </div>
  {% endif %}
</form>
<style>
  .bbox_image {
    max-height: 360px;  /* 이미지의 최대 높이를 100%로 설정 */
    max-width: 500px; /* 이미지의 최대 너비를 100%로 설정 */
    width: auto; /* 너비를 자동으로 조정하여 비율 유지 */
    height: auto; /* 높이를 자동으로 조정하여 비율 유지 */
    object-fit: contain; /* 이미지가 완전히 박스 내에 맞게 조정됨 */
  }
  .image-container {
    border: 1px solid #ccc; /* 테두리 스타일 지정 */
    padding: 10px; /* 내부 여백 설정 */
    display: flex;
  }
  .image-container h3{
    border: 1px solid #ccc; /* 테두리 스타일 지정 */
    padding: 10px; /* 내부 여백 설정 */
  }
  .img {
    max-width: 32vw;
    max-height: 35vh;
    width: auto; /* 너비를 자동으로 조정하여 비율 유지 */
    height: auto; /* 높이를 자동으로 조정하여 비율 유지 */
    object-fit: contain; /* 이미지가 완전히 박스 내에 맞게 조정됨 */
    justify-content: center;
  }
</style>
<script>
  window.onload = function () {
    // HTML 요소 가져오기
    const targetImageContainer = document.getElementById('target_image_container');
    const sourceImageContainer = document.getElementById('source_image_container');
    
    // data-mydata 속성에서 데이터 가져오기
    const targetBboxList = JSON.parse(targetImageContainer.getAttribute('data-mydata'));
    const sourceBboxList = JSON.parse(sourceImageContainer.getAttribute('data-mydata'));
    console.log(targetBboxList)
    console.log(sourceBboxList)
    
    function drawBoundingBoxes(container, bboxList, containerType) {
      // 이미지 요소 가져오기
      const image = container.querySelector('img');
          
      // 이미지의 원래 크기 가져오기
      const originalImageWidth = image.naturalWidth;
      const originalImageHeight = image.naturalHeight;
      
      // 이미지의 현재 크기 가져오기
      const currentImageWidth = image.width;
      const currentImageHeight = image.height;
      
      // 크기 비율 계산
      const widthRatio = currentImageWidth / originalImageWidth;
      const heightRatio = currentImageHeight / originalImageHeight;

      for (let i = 0; i < bboxList.length; i++) {
          
          const bbox = bboxList[i];
          console.log(bboxList[i])

          // Create a container div for the checkbox and image
          const contCheckbox = document.createElement("div");
          contCheckbox.className = "cont-checkbox";

          // Create the checkbox input element
          const checkboxInput = document.createElement("input");
          if (containerType == 'target'){
            checkboxInput.type = "checkbox";
            checkboxInput.id = `${containerType}-${i}`;
            checkboxInput.name = `${containerType}_checkbox`; // name 속성 설정
            checkboxInput.value = i; // value 속성 설정
            contCheckbox.className = "cont-checkbox";
          } else {
            checkboxInput.type = "radio";
            checkboxInput.id = `${containerType}-${i}`;
            checkboxInput.name = `${containerType}_checkbox`; // name 속성 설정
            checkboxInput.value = i; // value 속성 설정
            contCheckbox.className = "cont-checkbox";
            checkboxInput.required = true; // required 속성 추가
          }         
                   
          // Create the label element for checkbox
          const label = document.createElement("label");
          label.htmlFor = `${containerType}-${i}`;

          // Create the div for info text
          const infoDiv = document.createElement("div");
          infoDiv.className = "info";
          infoDiv.textContent = "Object " + i; // Replace with the appropriate label

          // bbox의 좌표를 이미지 크기에 맞게 조정
          const adjustedX = bbox[0] * widthRatio;
          const adjustedY = bbox[1] * heightRatio;
          const adjustedWidth = (bbox[2] - bbox[0]) * widthRatio;
          const adjustedHeight = (bbox[3] - bbox[1]) * heightRatio;

          // Set the position and size of the container div
          contCheckbox.style.position = "absolute";
          contCheckbox.style.left = adjustedX + "px";
          contCheckbox.style.top = adjustedY + "px";
          contCheckbox.style.width = adjustedWidth + "px";
          contCheckbox.style.height = adjustedHeight + "px";
          contCheckbox.style.border = "2px solid blue";

          // Append all elements to the container
          label.appendChild(contCheckbox);
          contCheckbox.appendChild(checkboxInput);

          // Add the container div to the specified container
          container.appendChild(label);

          // // 클릭 이벤트 처리 (각각의 사각형에 대해 클릭 이벤트 핸들러 생성)
          // contCheckbox.addEventListener("click", createClickHandler(i));
      }
    }

    // target와 source에 대해 BBox 그리기
    drawBoundingBoxes(targetImageContainer, targetBboxList, 'target');
    drawBoundingBoxes(sourceImageContainer, sourceBboxList, 'source');

    document.getElementById("swapform").addEventListener("submit", function(event) {
      var checkboxes = document.querySelectorAll('input[type="checkbox"]');
      var checked = false;
  
      checkboxes.forEach(function(checkbox) {
        if (checkbox.checked) {
          checked = true;
        }
      });
  
      if (!checked) {
        alert("체크박스에서 하나 이상의 옵션을 선택하세요.");
        event.preventDefault(); // 폼 제출을 취소합니다.
      }
    });

  }
</script>
{% endblock %}

server/templates/faceswap/img_upload.html
{% extends "base.html" %}
{% block content %}
<div id="root">
  <h1 class="title">원하는 얼굴 이미지 업로드</h1>
  <form method="POST" action="{% url 'faceswap:upload_img' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="contents">
      <div class="upload-box">
        <div id="drop-file" class="drag-file">
          <img src="https://img.icons8.com/pastel-glyph/2x/image-file.png" alt="파일 아이콘" class="image">
          <p class="message">Drag files to upload</p>
        </div>
        <!-- <label class="file-label" for="chooseFile">Choose File</label>
        <input class="file" id="chooseFile" type="file" multiple onchange="dropFile.handleFiles(this.files)"> -->
        <input type="hidden" name="target_image" value="{{ image_path }}">
        <label class="file-label" for="source_image">Choose File for Source Image</label>
        <input class="file" id="source_image" type="file" name="source_image" accept="image/*" onchange="dropFile.handleFiles(this.files)" required>
      </div>
      <div id="files" class="files">
      </div>

    </div>
    <hr>
    <div style="display: flex; justify-content: right;">
      <button type="submit" class="btn btn-success" style="width: 12rem">이미지 업로드</button>
    </div>
  </form>
</div>

<script>
  function DropFile(dropAreaId, fileListId) {
  let dropArea = document.getElementById(dropAreaId);
  let fileList = document.getElementById(fileListId);
  

  function preventDefaults(e) {
    e.preventDefault();
    e.stopPropagation();
  }

  function highlight(e) {
    preventDefaults(e);
    dropArea.classList.add("highlight");
  }

  function unhighlight(e) {
    preventDefaults(e);
    dropArea.classList.remove("highlight");
  }

  function handleDrop(e) {
    preventDefaults(e);
    // unhighlight(e);
    let dt = e.dataTransfer;
    let files = dt.files;

    // 드래그 앤 드롭으로 받은 파일을 input 요소에 할당
    document.getElementById("source_image").files = files;

    handleFiles(files);

    const fileList = document.getElementById(fileListId);
    if (fileList) {
      fileList.scrollTo({ top: fileList.scrollHeight });
    }
  }

  function handleFiles(files) {
    files = [...files];
    files.forEach(previewFile);
    files.forEach(previewImage);
  }

  function previewFile(file) {
    let filediv = fileList.childNodes[0]
    console.log(file);
    fileList.replaceChild(renderFile(file),filediv);
  }

  function renderFile(file) {
    let fileDOM = document.createElement("div");
    fileDOM.className = "file";
    fileDOM.id = "file";

    // 파일 크기를 받아옵니다.
    let fileSize = file.size;
    let fileSizeFormatted;

    // 파일 크기를 KB 또는 MB 단위로 변환합니다.
    if (fileSize < 1024) {
      fileSizeFormatted = fileSize + " B";
    } else if (fileSize < 1024 * 1024) {
      fileSizeFormatted = (fileSize / 1024).toFixed(2) + " KB";
    } else {
      fileSizeFormatted = (fileSize / (1024 * 1024)).toFixed(2) + " MB";
    }

    fileDOM.innerHTML = `
      <div class="thumbnail">
        <img src="https://img.icons8.com/pastel-glyph/2x/image-file.png" alt="파일타입 이미지" class="image">
      </div>
      <div class="details">
        <header class="header">
          <span class="name">${file.name}</span>
          <span class="size">${fileSizeFormatted}</span>
        </header>
        <div class="progress">
          <div class="bar"></div>
        </div>
        <div class="status">
          <span class="percent">100% done</span>
        </div>
      </div>
    `;
    return fileDOM;
  }

  function previewImage(file) {
    
    if (file.type.startsWith("image/")) {
      let reader = new FileReader();

      reader.onload = function(event) {
        let img = new Image();
        img.src = event.target.result;

        img.onload = function() {
          let maxWidth = 300;
          let maxHeight = 220;
          let width = img.width;
          let height = img.height;

          // 이미지 크기를 제한하고 비율을 유지합니다.
          if (width > maxWidth || height > maxHeight) {
            if (width / maxWidth > height / maxHeight) {
              width = maxWidth;
              height = width * (img.height / img.width);
            } else {
              height = maxHeight;
              width = height * (img.width / img.height);
            }
          }

          let thumbnail = document.createElement("img");
          thumbnail.src = event.target.result;
          thumbnail.alt = "이미지 미리보기";
          thumbnail.className = "thumbnail";
          thumbnail.style.maxWidth = maxWidth + "px";
          thumbnail.style.maxHeight = maxHeight + "px";
          thumbnail.style.width = width + "px";
          thumbnail.style.height = height + "px";

          // <div class="preview"> 요소를 가져옵니다.
          let fileListChildNode1 = fileList.childNodes[1]
          previewDiv = document.createElement("div");
          previewDiv.className = "file";

          // <div class="preview"> 요소가 존재하지 않으면 생성하고 썸네일을 추가합니다.
          if (!fileListChildNode1) {
            fileList.appendChild(previewDiv); // 혹은 다른 부모 요소에 추가할 수 있습니다.
            previewDiv.appendChild(thumbnail);
          } else{
            fileList.replaceChild(previewDiv,fileListChildNode1);
            previewDiv.appendChild(thumbnail);
          }
        };
      };

      reader.readAsDataURL(file);
    }
  }

  dropArea.addEventListener("dragenter", highlight, false);
  dropArea.addEventListener("dragover", highlight, false);
  dropArea.addEventListener("dragleave", unhighlight, false);
  dropArea.addEventListener("drop", handleDrop, false);

  return {
    handleFiles
  };
}

const dropFile = new DropFile("drop-file", "files");

</script>
{% endblock %}

server/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
    <div>
        <strong>{{ field.label }}</strong>
        {{ error }}
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}  <!-- 넌필드 오류를 출력한다. -->
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

server/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                    <a class="nav-link" href="{% url 'recommend:search' %}">메인페이지</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/I-fong/FFfusion" target="_blank">
                        <i class="fab fa-github"></i> GitHub
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

server/templates/recommend/search.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h1>
    <img src="{% static 'images/logo.png' %}" alt="무한짤봇 로고">
</h1>
<div class="container my-3">
    <form method="post" action="{% url 'recommend:search' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mx-auto w-50 mt-5 input-group mb-3">
          <input type="text" class="form-control" name="sentence" value="{{ form.sentence.value|default_if_none:'' }}"
                 placeholder="상대방에게 전하고 싶은 문장을 입력해주세요."
                 aria-label="상대방에게 전하고 싶은 문장을 입력해주세요."
                 aria-describedby="button-addon2">
          <button class="btn btn-outline-secondary" type="submit" id="button-addon2">짤 추천 받기</button>
        </div>
    </form>
</div>
{% endblock %}

server/templates/recommend/select.html
{% extends "base.html" %}
{% block content %}
<h4>
    원하는 이미지를 클릭해주세요.
</h4>
<div class="container my-3 mt-5">
    <form method="post" action="{% url 'recommend:select' %}" id="imageForm">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mx-auto row mt-3">
            {% for image_path in image_paths %}
                <div class="card" style="width: 20rem;">
                    <div class="card-body d-flex align-items-center justify-content-center">
                        <img src="{{ image_path }}" alt="Image {{ forloop.counter }}" class="img-thumbnail" onclick="submitImage('{{ image_path }}')">
                    </div>
                </div>
            {% endfor %}
        </div>
    </form>
</div>

{% endblock %}